### ISSUE TITLE
Error executing sync 

### ISSUE THREAD

**Issue by cheipol** [0x111/sn-edit.com#8]
I'm using v 0.1.2 on a windows 10 64bits and when I run `.\sn-edit-windows-amd64.exe sync` it crashes with:
```
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
time="2019-06-13T15:04:10+02:00" level=error msg="Query error" error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"
time="2019-06-13T15:04:10+02:00" level=info msg="Started watcher on the following Folder c:/sn-edit/sys_script_include"
time="2019-06-13T15:04:10+02:00" level=fatal msg="GetFileAttributes: The system cannot find the file specified."
```

**Comment by 0x111** [comment]
Yes, you are right. There was a configuration error with the build process and some flags got missing. This should be fixed now. I added new binaries and checksums to the release since there was no change in the codebase as such and it makes no sense to release new version just for this change. Could you please try the new binaries @cheipol and report back?
Thanks

**Comment by cheipol** [comment]
It seems to work with this new version. Thank you!
